from .classification import ClassificationAccuracyByClasses
from .segmentation import SegmentationIoUByClasses, SegmentationAccuracyByClasses
from .object_detection import DetectionIoUByClasses, RecallAndPrecision
from .keys import MetricKey
